### ISSUE TITLE
Design assets for Learning Pathways whitepaper

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#25] opened 2015-04-30 23:05 UTC
This issue has been migrated from mozilla/teach.webmaker.org#48.

It was originally written by [hannahkane](https://api.github.com/users/hannahkane) on Fri Feb 13 2015 and had the following description:

> Repo here: https://github.com/mozilla/learning-pathways-whitepaper/issues
> 
> Suggesting that **@****iamjessklein** might like to spend a heartbeat thinking through ways we can visualise the different types of learning pathways we discuss in the whitepaper _(forthcoming)_

On Thu Feb 26 2015, [dajbelshaw](https://api.github.com/users/dajbelshaw) commented:

> Specific issue is here: https://github.com/mozilla/learning-pathways-whitepaper/issues/26

On Tue Apr 21 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> What's the state of this? Is it still a need?

**Comment by hannahkane** [comment] 2015-07-21 23:10
dupe of #52

**Closed as completed by hannahkane** 2015-07-21 23:10 UTC
Labels: help wanted
